import pyautogui as py
py.press("win")
py.write("chrome")
py.press("enter")
py.sleep(2)
py.write("senai americana")
py.press("enter")
py.sleep(2)
py.click(229,465,button="left")
py.sleep(1)
py.click(368,262,button="left")
py.sleep(1)
py.click(270,321,button="left")
#py.sleep(4)
#print (py.position())
py.sleep(1)
py.click(202,492,button="left")
py.sleep(1)
py.click(202,492,button="left")
py.sleep(2)
py.write("Python")
py.sleep(1)
py.press("enter")
py.sleep(2)
py.vscroll(-500)
py.sleep(4)
print (py.position())
